import { ACCOUNTING_JOB_CATALOG } from "./jobCatalogAccounting.js";
import { PROMOTION_JOB_CATALOG } from "./jobCatalogPromotions.js"; import { CHANNELS_JOB_CATALOG } from "./jobCatalogChannels.js";
import { NO_LEDGER_JOB_EXCEPTIONS } from "./jobCatalogExceptions.js";
import type { JobCatalogEntry } from "./observabilityContracts.js";

export { NO_LEDGER_JOB_EXCEPTIONS };
const OBS_RUNBOOK = "/docs/platform/RUNTIME_AND_SELF_HOSTING.md";
const OMNIPACK_RUNBOOK = "/docs/platform/RUNTIME_AND_SELF_HOSTING.md";
const COMMUNICATIONS_RUNBOOK = "/docs/platform/RUNTIME_AND_SELF_HOSTING.md";
export const JOB_CATALOG: readonly JobCatalogEntry[] = [
  {
    jobName: "check-dhl-tracking",
    owner: "platform/fulfillment",
    severity: "p2",
    expectedEverySeconds: 12 * 60 * 60,
    startGraceSeconds: 90 * 60,
    finishGraceSeconds: 45 * 60,
    queueBacklogGraceSeconds: 6 * 60 * 60,
    runbookUrl: OBS_RUNBOOK,
    alertChannels: ["webhook"], requiresFlag: "COMMERCE_DHL_ONLY_DELIVERY",
  },
  {
    jobName: "omnipack-dispatch",
    owner: "commerce/fulfillment",
    // Money path: when this stops, paid orders are never handed to fulfillment, so its five job_* keys page at p0.
    severity: "p0",
    expectedEverySeconds: 60 * 60,
    startGraceSeconds: 30 * 60,
    finishGraceSeconds: 15 * 60,
    queueBacklogGraceSeconds: 60 * 60,
    runbookUrl: OMNIPACK_RUNBOOK,
    alertChannels: ["webhook"],
    requiresFlag: "COMMERCE_OMNIPACK_OBSERVABILITY_ENABLED",
  },
  {
    jobName: "omnipack-reconciliation",
    owner: "commerce/fulfillment",
    severity: "p1",
    expectedEverySeconds: 60 * 60,
    startGraceSeconds: 30 * 60,
    finishGraceSeconds: 15 * 60,
    runbookUrl: OMNIPACK_RUNBOOK,
    alertChannels: ["webhook"],
    requiresFlag: "COMMERCE_OMNIPACK_OBSERVABILITY_ENABLED",
  },
  {
    jobName: "omnipack-stock-sync",
    owner: "commerce/fulfillment",
    severity: "p1",
    expectedEverySeconds: 60 * 60,
    startGraceSeconds: 30 * 60,
    finishGraceSeconds: 15 * 60,
    runbookUrl: OMNIPACK_RUNBOOK,
    alertChannels: ["webhook"],
    requiresFlag: "COMMERCE_OMNIPACK_OBSERVABILITY_ENABLED",
  },
  {
    jobName: "omnipack-product-sync",
    owner: "commerce/fulfillment",
    severity: "p2",
    expectedEverySeconds: 6 * 60 * 60,
    startGraceSeconds: 60 * 60,
    finishGraceSeconds: 30 * 60,
    runbookUrl: OMNIPACK_RUNBOOK,
    alertChannels: ["webhook"],
    requiresFlag: "COMMERCE_OMNIPACK_OBSERVABILITY_ENABLED",
  },
  {
    // requiresFlag keeps the env-flag-off rollback path (the documented
    // long-duration kill) alert-silent; the seeded control row additionally
    // ships enabled=false, so monitoring needs BOTH switches on.
    jobName: "outbox-dispatch",
    owner: "commerce/platform",
    severity: "p1",
    expectedEverySeconds: 60,
    startGraceSeconds: 300,
    finishGraceSeconds: 300,
    queueBacklogGraceSeconds: 1800,
    runbookUrl: "/docs/platform/RUNTIME_AND_SELF_HOSTING.md",
    alertChannels: ["webhook", "resend"],
    requiresFlag: "COMMERCE_OUTBOX_DISPATCH_ENABLED",
  },
  {
    jobName: "outbox-prune",
    owner: "commerce/platform",
    severity: "p2",
    expectedEverySeconds: 24 * 60 * 60,
    startGraceSeconds: 6 * 60 * 60,
    finishGraceSeconds: 30 * 60,
    runbookUrl: "/docs/platform/RUNTIME_AND_SELF_HOSTING.md",
    alertChannels: ["webhook"],
    requiresFlag: "COMMERCE_OUTBOX_PRUNE_ENABLED",
  },
  {
    // Marketing Wave 3: enqueues abandoned-cart reminder outbox events every
    // 30 min (tightened from 6h so the 1h first-nudge tier is hit within ~30
    // min). requiresFlag keeps it alert-silent until the feature is switched on.
    jobName: "abandoned-cart-reminder",
    owner: "commerce/platform",
    severity: "p2",
    expectedEverySeconds: 30 * 60,
    startGraceSeconds: 30 * 60,
    finishGraceSeconds: 15 * 60,
    runbookUrl: OBS_RUNBOOK,
    alertChannels: ["webhook"],
    requiresFlag: "COMMERCE_ABANDONED_CART_ENABLED",
  },
  {
    // Checkout-recovery W2: enqueues commerce.checkout_recovery outbox events
    // (1h/20h nudges within the 24h window) for unpaid pending_payment orders.
    // Runs every 15 min; requiresFlag keeps it alert-silent until switched on.
    jobName: "checkout-recovery-dispatch",
    owner: "commerce/payment",
    severity: "p2",
    expectedEverySeconds: 15 * 60,
    startGraceSeconds: 15 * 60,
    finishGraceSeconds: 15 * 60,
    runbookUrl: OBS_RUNBOOK,
    alertChannels: ["webhook"],
    requiresFlag: "COMMERCE_CHECKOUT_RECOVERY_ENABLED",
  },
  {
    // Marketing Wave 5: enqueues post-delivery review request + effects review
    // outbox events. Daily scan; requiresFlag keeps it alert-silent until the
    // feature and dispatcher marketing readiness are both enabled.
    jobName: "review-request",
    owner: "commerce/platform",
    severity: "p2",
    expectedEverySeconds: 24 * 60 * 60,
    startGraceSeconds: 6 * 60 * 60,
    finishGraceSeconds: 30 * 60,
    runbookUrl: OBS_RUNBOOK,
    alertChannels: ["webhook"],
    requiresFlag: "COMMERCE_REVIEW_REQUEST_ENABLED",
  },
  {
    // Marketing P1b: enqueues reorder-reminder outbox events for one-time orders
    // delivered ~30 days ago whose customer hasn't reordered or subscribed. Runs
    // daily; requiresFlag keeps it alert-silent until the feature is switched on.
    jobName: "reorder-reminder",
    owner: "commerce/platform",
    severity: "p2",
    expectedEverySeconds: 24 * 60 * 60,
    startGraceSeconds: 6 * 60 * 60,
    finishGraceSeconds: 30 * 60,
    runbookUrl: OBS_RUNBOOK,
    alertChannels: ["webhook"],
    requiresFlag: "COMMERCE_REORDER_REMINDER_ENABLED",
  },
  {
    jobName: "communication-sync-dispatch",
    owner: "platform/communications",
    severity: "p2",
    expectedEverySeconds: 5 * 60,
    startGraceSeconds: 10 * 60,
    finishGraceSeconds: 10 * 60,
    queueBacklogGraceSeconds: 60 * 60,
    runbookUrl: COMMUNICATIONS_RUNBOOK,
    alertChannels: ["webhook"],
    requiresFlag: "COMMUNICATION_SYNC_DISPATCH_ENABLED",
  },
  {
    jobName: "communication-sync-reconcile",
    owner: "platform/communications",
    severity: "p2",
    expectedEverySeconds: 60 * 60,
    startGraceSeconds: 30 * 60,
    finishGraceSeconds: 15 * 60,
    runbookUrl: COMMUNICATIONS_RUNBOOK,
    alertChannels: ["webhook"],
    requiresFlag: "COMMUNICATION_SYNC_RECONCILE_ENABLED",
  },
  {
    jobName: "subscription-dunning-dispatch",
    owner: "commerce/subscription-support",
    severity: "p1",
    expectedEverySeconds: 10 * 60,
    startGraceSeconds: 5 * 60,
    finishGraceSeconds: 10 * 60,
    queueBacklogGraceSeconds: 15 * 60,
    runbookUrl: OBS_RUNBOOK,
    alertChannels: ["webhook", "resend"],
    requiresFlag: "COMMERCE_DUNNING_EMAILS_ENABLED",
  },
  {
    jobName: "subscription-pause-reminder",
    owner: "commerce/subscriptions",
    severity: "p2",
    expectedEverySeconds: 24 * 60 * 60,
    startGraceSeconds: 2 * 60 * 60,
    finishGraceSeconds: 30 * 60,
    queueBacklogGraceSeconds: 2 * 60 * 60,
    runbookUrl: OBS_RUNBOOK,
    alertChannels: ["webhook"],
    requiresFlag: "COMMERCE_SUBSCRIPTION_PAUSE_REMINDERS_ENABLED",
  },
  {
    jobName: "subscription-auto-resume",
    owner: "commerce/subscriptions",
    severity: "p2",
    expectedEverySeconds: 60 * 60,
    startGraceSeconds: 30 * 60,
    finishGraceSeconds: 15 * 60,
    runbookUrl: OBS_RUNBOOK,
    alertChannels: ["webhook"],
    requiresFlag: "COMMERCE_SUBSCRIPTION_RENEWAL_RUNTIME_ENABLED",
  },
  {
    jobName: "subscription-renewal-runtime",
    owner: "commerce/subscriptions",
    // Money path: when this stops, renewals cannot charge, so its five job_* keys page at p0.
    severity: "p0",
    expectedEverySeconds: 15 * 60,
    startGraceSeconds: 5 * 60,
    finishGraceSeconds: 15 * 60,
    runbookUrl: OBS_RUNBOOK,
    alertChannels: ["webhook"],
    requiresFlag: "COMMERCE_SUBSCRIPTION_RENEWAL_RUNTIME_ENABLED",
  },
  {
    jobName: "subscription-renewal-reminder",
    owner: "commerce/subscriptions",
    severity: "p2",
    expectedEverySeconds: 24 * 60 * 60,
    startGraceSeconds: 2 * 60 * 60,
    finishGraceSeconds: 30 * 60,
    runbookUrl: OBS_RUNBOOK,
    alertChannels: ["webhook"],
    requiresFlag: "SUBSCRIPTION_RENEWAL_REMINDER_ENABLED",
  },
  {
    jobName: "subscription-winback",
    owner: "commerce/subscriptions",
    severity: "p2",
    expectedEverySeconds: 24 * 60 * 60,
    startGraceSeconds: 2 * 60 * 60,
    finishGraceSeconds: 30 * 60,
    runbookUrl: OBS_RUNBOOK,
    alertChannels: ["webhook"],
    requiresFlag: "COMMERCE_SUBSCRIPTION_WINBACK_ENABLED",
  },
  {
    jobName: "subscription-activation-sweep-runtime",
    owner: "commerce/subscriptions",
    severity: "p2",
    expectedEverySeconds: 20 * 60,
    startGraceSeconds: 5 * 60,
    finishGraceSeconds: 15 * 60,
    runbookUrl: OBS_RUNBOOK,
    alertChannels: ["webhook"],
    requiresFlag: "COMMERCE_SUBSCRIPTION_SWEEP_ENABLED",
  },
  {
    jobName: "subscription-delivery-reminders",
    owner: "commerce/subscriptions",
    severity: "p2",
    expectedEverySeconds: 60 * 60,
    startGraceSeconds: 15 * 60,
    finishGraceSeconds: 15 * 60,
    runbookUrl: OBS_RUNBOOK,
    alertChannels: ["webhook"],
    requiresFlag: "COMMERCE_SUBSCRIPTION_DELIVERY_REMINDERS_ENABLED",
  },
  {
    jobName: "payment-provider-reconciliation",
    owner: "commerce/payment",
    severity: "p1",
    expectedEverySeconds: 30 * 60,
    startGraceSeconds: 10 * 60,
    finishGraceSeconds: 15 * 60,
    runbookUrl: OBS_RUNBOOK,
    alertChannels: ["webhook"],
    requiresFlag: "COMMERCE_PSP_OBSERVABILITY_ENABLED",
  },
  {
    jobName: "payment-stuck-processing-watchdog",
    owner: "commerce/payment",
    severity: "p1",
    evidenceModel: "effect_only",
    startGraceSeconds: 5 * 60,
    finishGraceSeconds: 10 * 60,
    runbookUrl: OBS_RUNBOOK,
    alertChannels: ["webhook"],
    requiresFlag: "COMMERCE_PSP_OBSERVABILITY_ENABLED",
  },
  {
    jobName: "commerce-reservation-sweep",
    owner: "commerce/payment",
    severity: "p2",
    expectedEverySeconds: 15 * 60,
    startGraceSeconds: 10 * 60,
    finishGraceSeconds: 10 * 60,
    runbookUrl: OBS_RUNBOOK,
    alertChannels: ["webhook"],
    requiresFlag: "COMMERCE_RESERVATION_SWEEP_ENABLED",
  },
  {
    jobName: "commerce-reservation-auto-expiry",
    owner: "commerce/payment",
    severity: "p2",
    expectedEverySeconds: 60 * 60,
    startGraceSeconds: 15 * 60,
    finishGraceSeconds: 15 * 60,
    runbookUrl: OBS_RUNBOOK,
    alertChannels: ["webhook"],
    requiresFlag: "COMMERCE_RESERVATION_AUTO_EXPIRY_ENABLED",
  },
  {
    jobName: "commerce-payment-event-sweep",
    owner: "commerce/payment",
    severity: "p2",
    expectedEverySeconds: 24 * 60 * 60,
    startGraceSeconds: 60 * 60,
    finishGraceSeconds: 60 * 60,
    runbookUrl: OBS_RUNBOOK,
    alertChannels: ["webhook"],
    requiresFlag: "COMMERCE_PAYMENT_EVENT_SWEEP_ENABLED",
  },
  ...PROMOTION_JOB_CATALOG, ...CHANNELS_JOB_CATALOG,
  ...ACCOUNTING_JOB_CATALOG,
  {
    // Trigger-reliability Wave 4: polls Resend for email_sends frozen at
    // 'sent' (dropped webhooks) and applies webhook-equivalent transitions.
    // requiresFlag keeps it alert-silent until the poller is switched on.
    jobName: "resend-delivery-reconciliation",
    owner: "platform/communications",
    severity: "p2",
    expectedEverySeconds: 30 * 60,
    startGraceSeconds: 30 * 60,
    finishGraceSeconds: 15 * 60,
    runbookUrl: OBS_RUNBOOK,
    alertChannels: ["webhook"],
    requiresFlag: "COMMERCE_RESEND_DELIVERY_RECONCILIATION_ENABLED",
  },
  {
    // Governed retention drain for the customer diagnostic corpus. No hosted
    // cron fires its route (platform.hostedCron: false); the in-process Node
    // scheduler and the GitHub poker are its clocks, so job_missed is the
    // detector that a clock stopped. requiresFlag keeps it alert-silent until
    // retention is switched on.
    jobName: "customer-diagnostic-prune",
    owner: "platform/observability",
    severity: "p2",
    expectedEverySeconds: 24 * 60 * 60,
    startGraceSeconds: 60 * 60,
    finishGraceSeconds: 60 * 60,
    runbookUrl: OBS_RUNBOOK,
    alertChannels: ["webhook"],
    requiresFlag: "COMMERCE_CUSTOMER_DIAGNOSTIC_PRUNE_ENABLED",
  },
];

export function jobCatalogByName(catalog: readonly JobCatalogEntry[] = JOB_CATALOG) {
  return new Map(catalog.map((job) => [job.jobName, job]));
}
