import {
  COMMERCE_ORDER_CANCELED_EVENT_TYPE,
  COMMERCE_ORDER_DRAFT_ABANDONED_1H_EVENT_TYPE,
  COMMERCE_ORDER_DRAFT_ABANDONED_24H_EVENT_TYPE,
  COMMERCE_ORDER_DRAFT_ABANDONED_72H_EVENT_TYPE,
  COMMERCE_ORDER_DRAFT_CREATED_EVENT_TYPE,
  COMMERCE_ORDER_PAID_EMAIL_EVENT_TYPE,
  COMMERCE_ORDER_PAID_EVENT_TYPE,
  COMMERCE_ORDER_REORDER_REMINDER_EVENT_TYPE,
  COMMERCE_CHECKOUT_RECOVERY_EVENT_TYPE,
  COMMERCE_CHECKOUT_EXPIRED_EVENT_TYPE,
  COMMERCE_RETURN_APPROVED_EVENT_TYPE,
  COMMERCE_RETURN_REJECTED_EVENT_TYPE,
  COMMERCE_ORDER_REFUNDED_EVENT_TYPE,
  COMMERCE_ORDER_REVIEW_EFFECTS_EVENT_TYPE,
  COMMERCE_ORDER_REVIEW_REQUEST_EVENT_TYPE,
  COMMERCE_PAYMENT_FAILED_EVENT_TYPE,
  COMMERCE_PRODUCT_BACK_IN_STOCK_EVENT_TYPE,
  COMMERCE_SHIPMENT_DELIVERED_EVENT_TYPE,
  COMMERCE_SHIPMENT_DISPATCHED_EVENT_TYPE,
  COMMERCE_SHIPMENT_EXCEPTION_EVENT_TYPE,
} from "../domains/commerce/outboxEventContracts.js";
import { ACCOUNTING_ORDER_REVERSAL_REQUESTED_EVENT_TYPE } from "../domains/accounting/outboxReversalContracts.js";
import {
  SUBSCRIPTION_CANCELLED_EVENT_TYPE,
  SUBSCRIPTION_CREATED_EVENT_TYPE,
  SUBSCRIPTION_ACTIVATION_ACTION_REQUIRED_EVENT_TYPE,
  SUBSCRIPTION_PAUSE_REMINDER_DUE_EVENT_TYPE,
  SUBSCRIPTION_PAUSED_EVENT_TYPE,
  SUBSCRIPTION_RESUMED_EVENT_TYPE,
  SUBSCRIPTION_DELIVERY_RESCHEDULED_EVENT_TYPE,
  SUBSCRIPTION_CYCLE_SKIPPED_EVENT_TYPE,
  SUBSCRIPTION_ADDRESS_CHANGED_EVENT_TYPE,
  SUBSCRIPTION_PACKAGE_CHANGED_EVENT_TYPE,
  SUBSCRIPTION_RENEWAL_UPCOMING_EVENT_TYPE,
} from "../domains/subscription/outboxEventContracts.js";
import { PERSONALIZATION_DECLENSION_REQUESTED_EVENT_TYPE } from "./personalizationDeclensionOutboxContract.js";
import { COMMERCE_FULFILLMENT_HANDED_OVER_EVENT_TYPE } from "./fulfillmentHandoffOutboxContract.js";

export const KNOWN_OUTBOX_EVENT_TYPES = [
  ACCOUNTING_ORDER_REVERSAL_REQUESTED_EVENT_TYPE,
  COMMERCE_ORDER_DRAFT_CREATED_EVENT_TYPE,
  COMMERCE_ORDER_PAID_EVENT_TYPE,
  COMMERCE_ORDER_PAID_EMAIL_EVENT_TYPE,
  COMMERCE_PAYMENT_FAILED_EVENT_TYPE,
  COMMERCE_CHECKOUT_EXPIRED_EVENT_TYPE,
  COMMERCE_RETURN_APPROVED_EVENT_TYPE,
  COMMERCE_RETURN_REJECTED_EVENT_TYPE,
  COMMERCE_ORDER_CANCELED_EVENT_TYPE,
  COMMERCE_ORDER_REFUNDED_EVENT_TYPE,
  COMMERCE_SHIPMENT_DISPATCHED_EVENT_TYPE,
  COMMERCE_SHIPMENT_DELIVERED_EVENT_TYPE,
  COMMERCE_SHIPMENT_EXCEPTION_EVENT_TYPE,
  COMMERCE_ORDER_REVIEW_REQUEST_EVENT_TYPE,
  COMMERCE_ORDER_REVIEW_EFFECTS_EVENT_TYPE,
  COMMERCE_PRODUCT_BACK_IN_STOCK_EVENT_TYPE,
  COMMERCE_ORDER_DRAFT_ABANDONED_1H_EVENT_TYPE,
  COMMERCE_ORDER_DRAFT_ABANDONED_24H_EVENT_TYPE,
  COMMERCE_ORDER_DRAFT_ABANDONED_72H_EVENT_TYPE,
  COMMERCE_ORDER_REORDER_REMINDER_EVENT_TYPE,
  COMMERCE_CHECKOUT_RECOVERY_EVENT_TYPE,
  SUBSCRIPTION_CANCELLED_EVENT_TYPE,
  SUBSCRIPTION_CREATED_EVENT_TYPE,
  SUBSCRIPTION_ACTIVATION_ACTION_REQUIRED_EVENT_TYPE,
  SUBSCRIPTION_PAUSE_REMINDER_DUE_EVENT_TYPE,
  SUBSCRIPTION_PAUSED_EVENT_TYPE,
  SUBSCRIPTION_RESUMED_EVENT_TYPE,
  SUBSCRIPTION_DELIVERY_RESCHEDULED_EVENT_TYPE,
  SUBSCRIPTION_CYCLE_SKIPPED_EVENT_TYPE,
  SUBSCRIPTION_ADDRESS_CHANGED_EVENT_TYPE,
  SUBSCRIPTION_PACKAGE_CHANGED_EVENT_TYPE,
  SUBSCRIPTION_RENEWAL_UPCOMING_EVENT_TYPE,
  PERSONALIZATION_DECLENSION_REQUESTED_EVENT_TYPE,
  COMMERCE_FULFILLMENT_HANDED_OVER_EVENT_TYPE,
] as const;

/**
 * Events whose consumer ships before any producer. They remain known so the
 * dispatcher can claim a future valid row, while the producer-contract guard
 * proves that this wave has not introduced an outbox emission path.
 */
export const CONSUMER_ONLY_OUTBOX_EVENT_TYPES = [
  ACCOUNTING_ORDER_REVERSAL_REQUESTED_EVENT_TYPE,
] as const;

// Re-export the individual event-type constants so boundary-neutral consumers
// (e.g. src/domains/communications/emailRoutingPolicy.ts) can source them from
// this hub instead of re-declaring the literals and risking producer↔routing
// drift. Re-export of already-imported locals (NOT `export ... from`) so no new
// module specifier enters this file's contract-purity scan.
export {
  ACCOUNTING_ORDER_REVERSAL_REQUESTED_EVENT_TYPE,
  COMMERCE_ORDER_DRAFT_CREATED_EVENT_TYPE,
  COMMERCE_ORDER_PAID_EMAIL_EVENT_TYPE,
  COMMERCE_PAYMENT_FAILED_EVENT_TYPE,
  COMMERCE_CHECKOUT_EXPIRED_EVENT_TYPE,
  COMMERCE_RETURN_APPROVED_EVENT_TYPE,
  COMMERCE_RETURN_REJECTED_EVENT_TYPE,
  COMMERCE_ORDER_CANCELED_EVENT_TYPE,
  COMMERCE_ORDER_REFUNDED_EVENT_TYPE,
  COMMERCE_SHIPMENT_DISPATCHED_EVENT_TYPE,
  COMMERCE_SHIPMENT_DELIVERED_EVENT_TYPE,
  COMMERCE_SHIPMENT_EXCEPTION_EVENT_TYPE,
  COMMERCE_ORDER_REVIEW_REQUEST_EVENT_TYPE,
  COMMERCE_ORDER_REVIEW_EFFECTS_EVENT_TYPE,
  COMMERCE_PRODUCT_BACK_IN_STOCK_EVENT_TYPE,
  COMMERCE_ORDER_DRAFT_ABANDONED_1H_EVENT_TYPE,
  COMMERCE_ORDER_DRAFT_ABANDONED_24H_EVENT_TYPE,
  COMMERCE_ORDER_DRAFT_ABANDONED_72H_EVENT_TYPE,
  COMMERCE_ORDER_REORDER_REMINDER_EVENT_TYPE,
  COMMERCE_CHECKOUT_RECOVERY_EVENT_TYPE,
  SUBSCRIPTION_CANCELLED_EVENT_TYPE,
  SUBSCRIPTION_CREATED_EVENT_TYPE,
  SUBSCRIPTION_ACTIVATION_ACTION_REQUIRED_EVENT_TYPE,
  SUBSCRIPTION_PAUSE_REMINDER_DUE_EVENT_TYPE,
  SUBSCRIPTION_PAUSED_EVENT_TYPE,
  SUBSCRIPTION_RESUMED_EVENT_TYPE,
  SUBSCRIPTION_DELIVERY_RESCHEDULED_EVENT_TYPE,
  SUBSCRIPTION_CYCLE_SKIPPED_EVENT_TYPE,
  SUBSCRIPTION_ADDRESS_CHANGED_EVENT_TYPE,
  SUBSCRIPTION_PACKAGE_CHANGED_EVENT_TYPE,
  SUBSCRIPTION_RENEWAL_UPCOMING_EVENT_TYPE,
  COMMERCE_FULFILLMENT_HANDED_OVER_EVENT_TYPE,
};
