export const COMMERCE_RECOMMENDATION_STATUSES = [
  "ready_to_buy",
  "warning",
  "manual_review",
] as const;

export const COMMERCE_RECOMMENDATION_REASON_CODES = [
  "energy_policy_fediaf_2025",
  "daily_kcal_override_used",
  "age_puppy",
  "age_young",
  "age_adult",
  "age_senior",
  "activity_low",
  "activity_normal",
  "activity_high",
  "bcs_thin",
  "bcs_ideal",
  "bcs_overweight",
  "puppy_not_supported",
  "allergen_conflict_excluded",
  "preferred_flavors_used",
  "safe_catalog_fallback_used",
  "fallback_limited_to_safe_alternatives",
  "no_safe_products",
  "catalog_variants_missing",
  "quantity_rounded_to_full_cans",
  "minimum_order_quantity_applied",
  "max_order_quantity_exceeded",
  "large_package_warning",
  "package_rebalanced_to_target_kcal",
  "stock_bounded_quantities_applied",
  "stock_limited_below_target",
  "additional_safe_flavor_selection_required",
] as const;
