import { describe, expect, it } from "vitest";

import { FLAG, GOVERNED_FLAG_NAMES, SECRET } from "./flagNames.js";

describe("flagNames", () => {
  it("maps each key to its exact governed env-var name", () => {
    expect(FLAG).toEqual({
      CHECKOUT_LIVE: "COMMERCE_V2_W11_CHECKOUT_LIVE",
      CONFIGURATOR_INTENT_PERSISTENCE: "COMMERCE_CONFIGURATOR_INTENT_PERSISTENCE_ENABLED",
      PRICING_RESOLVER: "COMMERCE_V2_W2_PRICING_RESOLVER",
      ALLOW_HIDDEN_REHEARSAL_PAYMENT: "COMMERCE_V2_W11_ALLOW_HIDDEN_REHEARSAL_PAYMENT",
      PROVIDER_PAYMENTS: "COMMERCE_PROVIDER_PAYMENTS_ENABLED",
      PROVIDER_WEBHOOKS: "COMMERCE_PROVIDER_WEBHOOKS_ENABLED",
      STRIPE_SANDBOX: "PAYMENTS_STRIPE_SANDBOX_ENABLED",
      TPAY: "PAYMENTS_TPAY_ENABLED",
      TPAY_SANDBOX: "PAYMENTS_TPAY_SANDBOX_ENABLED",
      TPAY_SIMULATOR: "PAYMENTS_TPAY_SIMULATOR_ENABLED",
      TPAY_VERIFIED_TEST_MODE: "PAYMENTS_TPAY_VERIFIED_TEST_MODE_ENABLED",
      TPAY_PRODUCTION: "PAYMENTS_TPAY_PRODUCTION_ENABLED",
      SUBSCRIPTION_CHECKOUT_CONTRACT: "COMMERCE_V2_W11_SUBSCRIPTION_CHECKOUT_CONTRACT_ENABLED",
      RISK_EVALUATION: "COMMERCE_RISK_EVALUATION_ENABLED",
      RISK_CHECKOUT_BLOCKLIST_BLOCKING: "COMMERCE_RISK_CHECKOUT_BLOCKLIST_BLOCKING_ENABLED",
      DHL_ONLY_DELIVERY: "COMMERCE_DHL_ONLY_DELIVERY",
      CUSTOMER_AUTH_UI: "COMMERCE_V2_W12_CUSTOMER_AUTH_UI",
      CUSTOMER_SELF_SERVICE: "COMMERCE_CUSTOMER_SELF_SERVICE_ENABLED",
      CUSTOMER_ADDRESSES: "COMMERCE_CUSTOMER_ADDRESSES_ENABLED",
      CUSTOMER_PREFERENCES: "COMMERCE_CUSTOMER_PREFERENCES_ENABLED",
      SUBSCRIPTION_MUTATIONS: "COMMERCE_SUBSCRIPTION_MUTATIONS_ENABLED",
      SUBSCRIPTION_GENERIC_BUNDLE_ACTIONS: "COMMERCE_SUBSCRIPTION_GENERIC_BUNDLE_ACTIONS_ENABLED",
      PSP_RECOVERY: "COMMERCE_PSP_RECOVERY_ENABLED",
      OUTBOX_DISPATCH: "COMMERCE_OUTBOX_DISPATCH_ENABLED",
      ACCOUNTING_PREVIEW_UI: "COMMERCE_ACCOUNTING_PREVIEW_UI_ENABLED",
      ACCOUNTING_TEST_PDF: "COMMERCE_ACCOUNTING_TEST_PDF_ENABLED",
      OFFER_POLICY_V2: "COMMERCE_OFFER_POLICY_V2_ENABLED",
      OFFER_POLICY_V1_FALLBACK_DISABLED: "COMMERCE_OFFER_POLICY_V1_FALLBACK_DISABLED",
      STARTER_PACK: "COMMERCE_STARTER_PACK_ENABLED",
    });
  });

  it("exposes secrets separately from governed flags", () => {
    expect(SECRET).toEqual({
      RISK_HASH: "COMMERCE_RISK_HASH_SECRET",
      PRICING_POLICY_TOKEN: "COMMERCE_PRICING_POLICY_TOKEN_SECRET",
      PROMOTION_ACCEPTANCE_HMAC: "COMMERCE_PROMOTION_ACCEPTANCE_HMAC_SECRET",
      PROMOTION_ACCEPTANCE_HMAC_PREVIOUS: "COMMERCE_PROMOTION_ACCEPTANCE_HMAC_SECRET_PREVIOUS",
    });
  });

  it("derives GOVERNED_FLAG_NAMES from FLAG values", () => {
    expect([...GOVERNED_FLAG_NAMES].sort()).toEqual(Object.values(FLAG).sort());
    expect(new Set(GOVERNED_FLAG_NAMES).size).toBe(GOVERNED_FLAG_NAMES.length);
  });
});
