/**
 * Literal feature-flag environment-variable names for the typed config service.
 *
 * Split out from featureFlags.ts so the service file stays under the source-file
 * LOC cap. Names are added here as call-sites migrate onto the service.
 *
 * Every name in {@link GOVERNED_FLAG_NAMES} is a boolean gate registered in
 * config/feature-flags.json (asserted by featureFlags.test.ts). Secret names
 * (e.g. RISK_HASH) are non-flag credentials and intentionally absent from that
 * registry, so they live under {@link SECRET} rather than {@link FLAG}.
 */

/** Governed boolean feature-flag env-var names (registered in config/feature-flags.json). */
export const FLAG = {
  CHECKOUT_LIVE: "COMMERCE_V2_W11_CHECKOUT_LIVE",
  CONFIGURATOR_INTENT_PERSISTENCE: "COMMERCE_CONFIGURATOR_INTENT_PERSISTENCE_ENABLED",
  PRICING_RESOLVER: "COMMERCE_V2_W2_PRICING_RESOLVER",
  ALLOW_HIDDEN_REHEARSAL_PAYMENT: "COMMERCE_V2_W11_ALLOW_HIDDEN_REHEARSAL_PAYMENT",
  PROVIDER_PAYMENTS: "COMMERCE_PROVIDER_PAYMENTS_ENABLED",
  PROVIDER_WEBHOOKS: "COMMERCE_PROVIDER_WEBHOOKS_ENABLED",
  STRIPE_SANDBOX: "PAYMENTS_STRIPE_SANDBOX_ENABLED",
  TPAY: "PAYMENTS_TPAY_ENABLED",
  TPAY_SANDBOX: "PAYMENTS_TPAY_SANDBOX_ENABLED",
  TPAY_SIMULATOR: "PAYMENTS_TPAY_SIMULATOR_ENABLED",
  TPAY_VERIFIED_TEST_MODE: "PAYMENTS_TPAY_VERIFIED_TEST_MODE_ENABLED",
  TPAY_PRODUCTION: "PAYMENTS_TPAY_PRODUCTION_ENABLED",
  SUBSCRIPTION_CHECKOUT_CONTRACT: "COMMERCE_V2_W11_SUBSCRIPTION_CHECKOUT_CONTRACT_ENABLED",
  RISK_EVALUATION: "COMMERCE_RISK_EVALUATION_ENABLED",
  RISK_CHECKOUT_BLOCKLIST_BLOCKING: "COMMERCE_RISK_CHECKOUT_BLOCKLIST_BLOCKING_ENABLED",
  DHL_ONLY_DELIVERY: "COMMERCE_DHL_ONLY_DELIVERY",
  CUSTOMER_AUTH_UI: "COMMERCE_V2_W12_CUSTOMER_AUTH_UI",
  CUSTOMER_SELF_SERVICE: "COMMERCE_CUSTOMER_SELF_SERVICE_ENABLED",
  CUSTOMER_ADDRESSES: "COMMERCE_CUSTOMER_ADDRESSES_ENABLED",
  CUSTOMER_PREFERENCES: "COMMERCE_CUSTOMER_PREFERENCES_ENABLED",
  SUBSCRIPTION_MUTATIONS: "COMMERCE_SUBSCRIPTION_MUTATIONS_ENABLED",
  SUBSCRIPTION_GENERIC_BUNDLE_ACTIONS: "COMMERCE_SUBSCRIPTION_GENERIC_BUNDLE_ACTIONS_ENABLED",
  PSP_RECOVERY: "COMMERCE_PSP_RECOVERY_ENABLED",
  OUTBOX_DISPATCH: "COMMERCE_OUTBOX_DISPATCH_ENABLED",
  ACCOUNTING_PREVIEW_UI: "COMMERCE_ACCOUNTING_PREVIEW_UI_ENABLED",
  ACCOUNTING_TEST_PDF: "COMMERCE_ACCOUNTING_TEST_PDF_ENABLED",
  OFFER_POLICY_V2: "COMMERCE_OFFER_POLICY_V2_ENABLED",
  OFFER_POLICY_V1_FALLBACK_DISABLED: "COMMERCE_OFFER_POLICY_V1_FALLBACK_DISABLED",
  STARTER_PACK: "COMMERCE_STARTER_PACK_ENABLED",
} as const;

/** Non-flag secret env-var names read by the service (not in the flag registry). */
export const SECRET = {
  RISK_HASH: "COMMERCE_RISK_HASH_SECRET",
  PRICING_POLICY_TOKEN: "COMMERCE_PRICING_POLICY_TOKEN_SECRET",
  PROMOTION_ACCEPTANCE_HMAC: "COMMERCE_PROMOTION_ACCEPTANCE_HMAC_SECRET",
  PROMOTION_ACCEPTANCE_HMAC_PREVIOUS: "COMMERCE_PROMOTION_ACCEPTANCE_HMAC_SECRET_PREVIOUS",
} as const;

/** Flat list of governed boolean flag names, for registry-discoverability assertions. */
export const GOVERNED_FLAG_NAMES: readonly string[] = Object.values(FLAG);
