/** @beta Vocabulary ownership is separate from consumer registration. */
export interface EventVocabularyEntry { eventType: string; owner: string }
/** @beta Applications supply their complete ordered persisted vocabulary separately. */
export const PLATFORM_EVENT_VOCABULARY: readonly EventVocabularyEntry[] = [
  { eventType: "commerce.order_draft.created", owner: "@openlup/core" },
  { eventType: "commerce.order.paid", owner: "@openlup/core" },
  { eventType: "commerce.order.paid.email", owner: "@openlup/core" },
  { eventType: "commerce.payment.failed", owner: "@openlup/core" },
  { eventType: "commerce.checkout.expired", owner: "@openlup/core" },
  { eventType: "commerce.order.canceled", owner: "@openlup/core" },
  { eventType: "commerce.order.refunded", owner: "@openlup/core" },
  { eventType: "commerce.shipment.dispatched", owner: "@openlup/core" },
  { eventType: "commerce.shipment.delivered", owner: "@openlup/core" },
  { eventType: "commerce.shipment.exception", owner: "@openlup/core" },
  { eventType: "commerce.return.approved", owner: "@openlup/core" },
  { eventType: "commerce.return.rejected", owner: "@openlup/core" },
  { eventType: "commerce.order.review_request", owner: "@openlup/core" },
  { eventType: "commerce.order.review_effects", owner: "@openlup/core" },
  { eventType: "commerce.product.back_in_stock", owner: "@openlup/core" },
  { eventType: "commerce.order_draft.abandoned.1h", owner: "@openlup/core" },
  { eventType: "commerce.order_draft.abandoned.24h", owner: "@openlup/core" },
  { eventType: "commerce.order_draft.abandoned.72h", owner: "@openlup/core" },
  { eventType: "commerce.order.reorder_reminder", owner: "@openlup/core" },
  { eventType: "commerce.checkout_recovery", owner: "@openlup/core" },
  { eventType: "subscription.cancelled", owner: "@openlup/core" },
  { eventType: "subscription.created", owner: "@openlup/core" },
  { eventType: "subscription.activation_action_required", owner: "@openlup/core" },
  { eventType: "subscription.pause_reminder_due", owner: "@openlup/core" },
  { eventType: "subscription.paused", owner: "@openlup/core" },
  { eventType: "subscription.resumed", owner: "@openlup/core" },
  { eventType: "subscription.delivery_rescheduled", owner: "@openlup/core" },
  { eventType: "subscription.cycle_skipped", owner: "@openlup/core" },
  { eventType: "subscription.address_changed", owner: "@openlup/core" },
  { eventType: "subscription.package_changed", owner: "@openlup/core" },
  { eventType: "subscription.renewal_upcoming", owner: "@openlup/core" },
  { eventType: "accounting.order.reversal_requested", owner: "@openlup/core" },
  { eventType: "commerce.fulfillment.handed_over", owner: "@openlup/core" },
];
