import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { dirname, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import ts from "typescript";
import { assertPackageSurfaceConfig } from "./public-api-config.ts";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const distRoot = resolve(packageRoot, "dist");
const gates = readJson("release-gates.json");
const update = process.argv.includes("--update");
let snapshotsChanged = false;

assertPackageSurfaceConfig({
  manifest: readJson("package.json"),
  gates,
  packageRoot,
  requireSnapshots: !update,
});

for (const [subpath, contract] of Object.entries(gates.packageSurface)) {
  const entrypoint = resolveInsidePackage(contract.entrypoint);
  const snapshotPath = resolveInsidePackage(contract.snapshot);
  assert(existsSync(entrypoint), `missing declaration entrypoint ${contract.entrypoint}; run npm run build`);

  const snapshot = renderSnapshot(subpath, contract, entrypoint);
  if (update) {
    const previous = existsSync(snapshotPath) ? readFileSync(snapshotPath, "utf8") : undefined;
    snapshotsChanged ||= previous !== snapshot;
    mkdirSync(dirname(snapshotPath), { recursive: true });
    writeFileSync(snapshotPath, snapshot);
    console.log(`updated ${contract.snapshot}`);
    continue;
  }

  assert(existsSync(snapshotPath), `missing API snapshot ${contract.snapshot}; run npm run api:update`);
  const expected = readFileSync(snapshotPath, "utf8");
  assert(
    expected === snapshot,
    `${contract.maturity} package surface drift for ${subpath}; review declarations and run npm run api:update intentionally`,
  );
  console.log(`${contract.maturity} package surface ok ${subpath}`);
}

if (update && snapshotsChanged) assertChangelogChanged();

function renderSnapshot(subpath, contract, entrypoint) {
  const declarations = collectDeclarationGraph(entrypoint);
  const sections = declarations.map((file) => {
    const path = toPosix(relative(packageRoot, file));
    const source = readFileSync(file, "utf8").trimEnd();
    return `## ${path}\n\n\`\`\`ts\n${source}\n\`\`\``;
  });

  return [
    `# ${subpath} API declaration snapshot`,
    "",
    `Maturity: **${contract.maturity}**.`,
    "",
    gates.compatibilityPolicies[contract.compatibilityPolicy],
    "",
    "Generated by `npm run api:update`. Every change requires explicit review.",
    "",
    ...sections,
    "",
  ].join("\n");
}

function collectDeclarationGraph(entrypoint) {
  const found = new Set();
  const pending = [entrypoint];

  while (pending.length > 0) {
    const file = pending.pop();
    if (found.has(file)) continue;
    assert(file.startsWith(`${distRoot}${sep}`), `declaration escaped dist: ${file}`);
    assert(existsSync(file), `missing referenced declaration ${toPosix(relative(packageRoot, file))}`);
    found.add(file);

    const source = ts.createSourceFile(
      file,
      readFileSync(file, "utf8"),
      ts.ScriptTarget.Latest,
      true,
      ts.ScriptKind.TS,
    );

    visit(source, (specifier) => {
      if (!specifier.startsWith(".")) return;
      const target = resolveDeclaration(file, specifier);
      assert(target, `cannot resolve ${specifier} from ${toPosix(relative(packageRoot, file))}`);
      pending.push(target);
    });
  }

  return [...found].sort((left, right) => left.localeCompare(right));
}

function visit(node, onModuleSpecifier) {
  if (
    (ts.isImportDeclaration(node) || ts.isExportDeclaration(node)) &&
    node.moduleSpecifier &&
    ts.isStringLiteral(node.moduleSpecifier)
  ) {
    onModuleSpecifier(node.moduleSpecifier.text);
  } else if (ts.isImportTypeNode(node)) {
    const argument = node.argument;
    if (ts.isLiteralTypeNode(argument) && ts.isStringLiteral(argument.literal)) {
      onModuleSpecifier(argument.literal.text);
    }
  }
  ts.forEachChild(node, (child) => visit(child, onModuleSpecifier));
}

function resolveDeclaration(fromFile, specifier) {
  const raw = resolve(dirname(fromFile), specifier);
  const candidates = specifier.endsWith(".js")
    ? [raw.slice(0, -3) + ".d.ts"]
    : [raw, `${raw}.d.ts`, resolve(raw, "index.d.ts")];
  return candidates.find((candidate) => existsSync(candidate));
}

function resolveInsidePackage(path) {
  const absolute = resolve(packageRoot, path);
  assert(
    absolute === packageRoot || absolute.startsWith(`${packageRoot}${sep}`),
    `path escapes package root: ${path}`,
  );
  return absolute;
}

function assertChangelogChanged() {
  const status = execFileSync("git", ["status", "--porcelain=v1", "--", "CHANGELOG.md"], {
    cwd: packageRoot,
    encoding: "utf8",
  });
  assert(
    status.trim().length > 0,
    "API snapshots changed; update CHANGELOG.md before completing npm run api:update",
  );
}

function readJson(path) {
  return JSON.parse(readFileSync(resolveInsidePackage(path), "utf8"));
}

function toPosix(path) {
  return path.split(sep).join("/");
}

function assert(condition, message) {
  if (!condition) throw new Error(message);
}
