import type { EmailCanonEntry } from "./emailCanon.js";
import { applyEmailCanonVerification } from "./emailCanonVerification.js";

export const EMAIL_LIFECYCLE_PLANNED_CANON_ENTRIES = [
  applyEmailCanonVerification({
    slug: "account-deletion-confirmation",
    owner: "customer-account",
    recipientKind: "customer",
    customerFacing: true,
    triggerSource: "account deletion / RODO workflow",
    triggerEvent: "account deletion or RODO request confirmed",
    renderer: "canonical_renderer",
    originPolicy: "app_origin_required",
    ledgerSource: "planned email_sends + delivery_timeline",
    timing: "immediate after account deletion/RODO confirmation",
    idempotencyPolicy: "one send per completed request id",
    testCoverage: "lifecycle decision target guard",
    status: "planned_send",
    localePolicy: "pl_en",
    inventoryStatus: "planned",
    deliveryStatus: "contract_only",
    policyFailureMode: "fail_closed",
  }),
  applyEmailCanonVerification({
    slug: "subscription-card-expiring",
    owner: "subscriptions",
    recipientKind: "customer",
    customerFacing: true,
    triggerSource: "subscription billing provider signal",
    triggerEvent: "trusted card expiry signal received",
    renderer: "canonical_renderer",
    originPolicy: "app_origin_required",
    ledgerSource: "planned email_sends + delivery_timeline",
    timing: "when provider expiry signal is actionable",
    idempotencyPolicy: "one send per payment method expiry window",
    testCoverage: "lifecycle decision target guard",
    status: "planned_send",
    localePolicy: "pl_en",
    inventoryStatus: "planned",
    deliveryStatus: "contract_only",
    policyFailureMode: "fail_closed",
  }),
  applyEmailCanonVerification({
    slug: "subscription-dunning-admin-escalation",
    owner: "operations",
    recipientKind: "admin_internal",
    customerFacing: false,
    triggerSource: "subscription dunning",
    triggerEvent: "dunning threshold reached",
    renderer: "operational_variant",
    originPolicy: "no_customer_cta",
    ledgerSource: "planned email_sends + delivery_timeline",
    timing: "after configured risk threshold",
    idempotencyPolicy: "one alert per subscription threshold window",
    testCoverage: "lifecycle decision target guard",
    status: "planned_send",
    localePolicy: "pl_only_launch_market",
    inventoryStatus: "planned",
    deliveryStatus: "contract_only",
    policyFailureMode: "fail_open_with_audit",
  }),
] as const satisfies readonly EmailCanonEntry[];
