// Generator for the Wave 2b catalog-content seed migration.
//
// Emits an idempotent migration that enriches each existing catalog_products row's
// `marketing_content` with the rich `content` blob (displayName / lineName / species
// / route / composition / metadata, PL+EN), derived from the SAME static source and
// SAME serializer (`serializeCatalogProductContent`) the DB read port reads back and
// the parity test (`catalogReadParity.test.ts`) asserts. Generating from one source
// guarantees the seeded rows reproduce the static catalog exactly at cutover (Wave 3).
//
// Idempotent: `marketing_content || jsonb_build_object('content', …)` overwrites only
// the `content` key on every apply, and UPDATE-by-slug is a no-op for rows that don't
// exist (e.g. a fresh CI database with no seeded catalog).
//
// To regenerate the migration after the static catalog changes, run the pure
// `buildCatalogContentSeedSql(catalogProducts)` from a context that can import the
// static catalog chain (the repo's vitest harness) and write the result to
// supabase/migrations/<ts>_catalog_content_seed.sql.

import {
  serializeCatalogProductContent,
  CATALOG_CONTENT_KEY,
} from "../src/domains/catalog/catalogContentSerialization.js";
import type { CatalogProduct } from "../src/domains/catalog/types.js";

function sqlString(value: string): string {
  return value.replace(/'/g, "''");
}

export function buildCatalogContentSeedSql(products: CatalogProduct[]): string {
  const header = `-- commerce-v2 Wave 2b: catalog content seed (generated)
--
-- Enriches each catalog_products row's marketing_content with the rich \`content\`
-- blob the DB-backed read port (server/domains/catalog/catalogAssembler.ts)
-- reads back, so the DB catalog reproduces the static catalog exactly at the
-- Wave 3 cutover. Generated by scripts/generate-catalog-content-seed.ts from the
-- static catalog (src/data/catalog.ts) via serializeCatalogProductContent — the
-- same serializer the parity test asserts.
--
-- Safety: data-only, additive merge. \`marketing_content || jsonb_build_object(...)\`
-- overwrites only the \`content\` key (idempotent on re-apply); UPDATE-by-slug is a
-- no-op for absent rows (fresh CI db). No schema change, no row creation, no deletes.
-- DO NOT EDIT BY HAND — regenerate via the script above.
`;

  const statements = products.map((product) => {
    const content = serializeCatalogProductContent(product)[CATALOG_CONTENT_KEY];
    const json = sqlString(JSON.stringify(content));
    const slug = sqlString(product.slug);
    return `UPDATE public.catalog_products
   SET marketing_content = marketing_content || jsonb_build_object('content', '${json}'::jsonb),
       updated_at = now()
 WHERE slug = '${slug}';`;
  });

  return `${header}\n${statements.join("\n\n")}\n`;
}
