import { describe, expect, it } from "vitest";
import { canonicalDigest, inventoryBase, type ConsumerReceipt } from "./oss-consumer-state.ts";
import { applyConsumePlan, candidateDigest, createConsumePlan, parseConsumePlan, type Adapter, type AuthenticatedCandidate, type Inputs } from "./oss-consume-engine.ts";

const d = (x: string) => canonicalDigest(x), sha = "a".repeat(40), blob = (path: string, value: string, mode: "100644" | "100755" = "100644") => ({ path, digest: d(value), mode });
const baseRows = [blob("a.ts", "a")];
const receipt = (active = false, rows = baseRows): ConsumerReceipt => ({ schemaVersion: 2, state: active ? "active" : "pre-split", waveMarker: "wave", source: { repository: active ? "https://github.com/a/b" : null, protectedRef: active ? "main" : null, rulesetIds: active ? [1] : [], releaseTagPrefix: "openlup-source-preview/", assetName: "openlup-source-receipt.json" }, reviewPolicy: { metricVersion: "git-diff-v1", measurementSha: sha, windowSize: 1, limits: { paths: 2, hunks: 2, patchBytes: 2 } }, pinMarkers: [], classes: { localMeasurement: [], projected: [] }, lastConsume: active ? { repository: "https://github.com/a/b", releaseTag: "openlup-source-preview/1", releaseImmutable: true, assetName: "openlup-source-receipt.json", assetId: 1, assetDigest: d("asset"), previousPublicSha: null, targetPublicSha: sha, targetTree: sha, publicContractDigest: d("contract"), sourceReceiptDigest: d("receipt"), downstreamBase: inventoryBase(rows.map(({ path, digest }) => ({ path, blobDigest: digest }))), changePathDigest: d("paths"), patchDigest: d("patch"), metrics: { paths: 1, hunks: 1, patchBytes: 1 }, changeSetDigest: d("old"), executionPlanDigest: d("old-plan") } : null });
const candidate = (patch: Partial<AuthenticatedCandidate> = {}): AuthenticatedCandidate => { const value = { schemaVersion: 1 as const, evidenceClass: "production-github" as const, receiptDigest: d("receipt"), release: { repository: "https://github.com/a/b", tag: "openlup-source-preview/1", assetName: "openlup-source-receipt.json", assetId: 1, assetDigest: d("asset"), immutable: true as const }, public: { previousSha: null, targetSha: sha, targetTree: sha, contractDigest: d("contract"), old: [blob("a.ts", "old")], target: baseRows, renames: [], changePathDigest: d("paths"), patchDigest: d("patch"), metrics: { paths: 1, hunks: 1, patchBytes: 1 }, expectedResultDigest: d("result") }, ci: { repository: "https://github.com/a/b", protectedRef: "main", rulesetIds: [1], contexts: [{ name: "check", conclusion: "success" as const, sha }], targetSha: sha, digest: d("ci") }, drift: { previous: [], target: [] }, ...patch } as Omit<AuthenticatedCandidate, "digest">; return { ...value, digest: candidateDigest(value) }; };
const input = (patch: Partial<Inputs> = {}): Inputs => ({ receipt: receipt(), snapshot: { head: sha, indexDigest: d("index"), treeDigest: d("tree"), controlDigests: { receipt: d("control") }, consumable: baseRows }, candidate: candidate(), facts: { migrations: [], emergency: [] }, assess: () => ({ status: "prepared", reviewedChangeSet: false, issues: [] }), ...patch });
describe("consume engine", () => {
  it("accepts equal bootstrap and detects mode-only changes", () => { expect(createConsumePlan(input()).status).toBe("ready"); const c = candidate({ public: { ...candidate().public, old: baseRows, target: [blob("a.ts", "a", "100755")] } }); expect(createConsumePlan(input({ candidate: c })).changes).toMatchObject([{ kind: "modify", beforeMode: "100644", afterMode: "100755" }]); });
  it("refuses chain, ordering, and public check defects", () => { const active = receipt(true), snap = { ...input().snapshot, consumable: baseRows }, publicBase = { ...candidate().public, previousSha: sha, old: baseRows, target: [blob("a.ts", "b")] }, chainGap = candidate({ public: { ...publicBase, previousSha: null } }), unsorted = candidate({ public: { ...candidate().public, old: [blob("z", "a"), blob("a", "a")] } }), badCi = candidate({ ci: { ...candidate().ci, contexts: [{ name: "x", conclusion: "success", sha }, { name: "x", conclusion: "success", sha }] } }), otherRepo = "https://github.com/a/c", repoGap = candidate({ public: publicBase, release: { ...candidate().release, repository: otherRepo }, ci: { ...candidate().ci, repository: otherRepo } }), refGap = candidate({ public: publicBase, ci: { ...candidate().ci, protectedRef: "other" } }), rulesGap = candidate({ public: publicBase, ci: { ...candidate().ci, rulesetIds: [2] } }); const refused = (candidate: AuthenticatedCandidate) => expect(createConsumePlan(input({ receipt: active, snapshot: snap, candidate })).status).toBe("refused"); refused(chainGap); refused(repoGap); refused(refGap); refused(rulesGap); expect(createConsumePlan(input({ candidate: unsorted })).status).toBe("refused"); expect(createConsumePlan(input({ candidate: badCi })).status).toBe("refused"); });
  it("honors receipt drift, injected dispositions, review, and fixture", () => {
    const old = [blob("derived/a", "1"), blob("em/a", "1"), blob("sql/a", "1")];
    const target = [blob("derived/a", "2"), blob("em/a", "2"), blob("sql/a", "2")];
    const c = candidate({ public: { ...candidate().public, previousSha: sha, old, target }, drift: { previous: [{ class: "projection", selector: "derived/" }], target: [{ class: "projection", selector: "derived/" }] } });
    const activeReceipt = receipt(true, old.slice(1)); activeReceipt.classes.projected = [{ selector: "derived/", reason: "projection" }];
    let assessed = ""; const plan = createConsumePlan(input({ receipt: activeReceipt, snapshot: { ...input().snapshot, consumable: old.slice(1) }, candidate: c, facts: { migrations: ["sql/"], emergency: ["em/"] }, assess: (_, changeSetDigest) => { assessed = changeSetDigest; return { status: "prepared", reviewedChangeSet: false, issues: [] }; } }));
    const fixture = candidate({ evidenceClass: "local-fixture" });
    const review = candidate({ public: { ...candidate().public, previousSha: sha, old: baseRows, target: [blob("a.ts", "b")], metrics: { paths: 3, hunks: 1, patchBytes: 1 } } });
    expect(plan.changes.map((x) => x.disposition).sort()).toEqual(["emergency-reconciliation", "prepared-migration-group", "prepared-projection"]);
    expect(plan.nextReceipt!.lastConsume!.downstreamBase.pathCount).toBe(2);
    expect(assessed).toBe(plan.changeSetDigest);
    expect(createConsumePlan(input({ candidate: fixture })).status).toBe("no-op");
    const reviewInput = { receipt: receipt(true), snapshot: { ...input().snapshot, consumable: baseRows }, candidate: review }; expect(createConsumePlan(input(reviewInput)).status).toBe("review-required"); expect(createConsumePlan(input({ ...reviewInput, assess: () => ({ status: "prepared", reviewedChangeSet: true, issues: [] }) })).status).toBe("ready");
  });
  it("permits absent local measurement declarations and refuses class transitions", () => { const absent = candidate({ drift: { previous: [], target: [{ class: "local-measurement", selector: "private-only/" }] } }), pre = receipt(); pre.classes.localMeasurement = [{ selector: "private-only/", reason: "local" }]; expect(createConsumePlan(input({ receipt: pre, candidate: absent })).status).toBe("ready"); const old = [blob("x", "a")], target = [blob("x", "b")], changing = candidate({ public: { ...candidate().public, previousSha: sha, old, target }, drift: { previous: [{ class: "projection", selector: "x" }], target: [{ class: "local-measurement", selector: "x" }] } }), active = receipt(true, []); active.classes.projected = [{ selector: "x", reason: "projection" }]; expect(createConsumePlan(input({ receipt: active, snapshot: { ...input().snapshot, consumable: [] }, candidate: changing })).status).toBe("refused"); });
  it("strictly parses and fails closed for adapter faults", async () => {
    const p = createConsumePlan(input());
    expect(parseConsumePlan(JSON.stringify(p)).marker).toBe(p.marker);
    const tampered = { ...p, candidate: { ...p.candidate, public: { ...p.candidate.public, old: [{ ...p.candidate.public.old[0]!, extra: true }] } } };
    expect(() => parseConsumePlan(JSON.stringify(tampered))).toThrow();
    const adapter: Adapter = { snapshot: async () => input().snapshot, reauthenticate: async () => p.candidate, authorize: async () => true, trial: async () => ({ ok: true, digest: d("result") }), publish: async () => ({ ok: true, proofDigest: p.publicationProofDigest! }), rollback: async () => true };
    expect((await applyConsumePlan(p, adapter)).mutation).toBe("applied");
    let trialled = false; const forged = await applyConsumePlan(p, { ...adapter, authorize: async () => false, trial: async () => { trialled = true; return { ok: true, digest: d("result") }; } }); expect(forged).toMatchObject({ code: "stale-preimage", mutation: "none" }); expect(trialled).toBe(false);
    expect((await applyConsumePlan(p, { ...adapter, trial: async () => { throw new Error("x"); } })).code).toBe("trial-refused");
    expect((await applyConsumePlan(p, { ...adapter, publish: async () => { throw new Error("x"); }, rollback: async () => { throw new Error("x"); } })).mutation).toBe("recovery-required");
  });
});
