import { localized, type SubscriptionDunningEmailContent } from "./subscriptionEmailContent.js";
const greetings = { pl: (name: string | null) => name ? `Cześć ${name},` : "Dzień dobry,", en: (name: string | null) => name ? `Hi ${name},` : "Hello," };
const method = (scheme: string, digits: string) => `${scheme.charAt(0).toUpperCase()}${scheme.slice(1)} •••• ${digits}`;

export const exampleSubscriptionDunningEmailContent = {
  paymentExpired: localized(greetings,
    (greeting) => ({ subject: "Subskrypcja została wstrzymana", preheader: "Skontaktuj się z obsługą, aby wznowić subskrypcję.", preheaderWithCta: "Zaktualizuj płatność i wznów subskrypcję.", heading: "Subskrypcja wstrzymana", greeting, intro: "Po kilku nieudanych próbach płatności subskrypcja została wstrzymana.", detail: (amount) => [amount ? `Nieopłacony cykl: ${amount}.` : "Ostatni cykl pozostał nieopłacony.", "Ustawienia subskrypcji zostały zachowane. Obsługa może pomóc w jej wznowieniu."], ctaDetail: "Nie pobierzemy zaległej opłaty automatycznie. Zaktualizuj metodę płatności, aby rozpocząć nowy cykl.", cta: "Zaktualizuj płatność i wznów", outro: "Jeśli potrzebujesz pomocy lub chcesz anulować subskrypcję, odpowiedz na tę wiadomość." }),
    (greeting) => ({ subject: "Your subscription was paused", preheader: "Contact support to resume your subscription.", preheaderWithCta: "Update payment and resume your subscription.", heading: "Subscription paused", greeting, intro: "After several unsuccessful payment attempts, the subscription was paused.", detail: (amount) => [amount ? `Unpaid cycle: ${amount}.` : "The latest cycle remains unpaid.", "Your subscription settings are preserved. Support can help you resume it."], ctaDetail: "We will not collect the overdue payment automatically. Update your payment method to start a new cycle.", cta: "Update payment and resume", outro: "Reply if you need help or want to cancel the subscription." }),
  ),
  paymentFailed: localized(greetings,
    (greeting) => ({ subject: "Płatność za subskrypcję nie powiodła się", preheader: "Sprawdź metodę płatności, aby utrzymać aktywną subskrypcję.", heading: "Nie udało się pobrać płatności", greeting, intro: "Nie udało się pobrać opłaty za kolejny cykl subskrypcji.", amountLine: (amount) => `Kwota: ${amount}.`, noAmountLine: "Spróbujemy pobrać opłatę ponownie.", noAmountLineNoRetry: "Ten cykl pozostaje nieopłacony.", methodLine: (scheme, digits) => `Metoda płatności: ${method(scheme, digits)}.`, reassurance: (attempt, date) => attempt >= 3 ? date ? `Ostatnia automatyczna próba nastąpi za 7 dni, ${date}. Jeśli się nie powiedzie, subskrypcja zostanie wstrzymana.` : "Ostatnia automatyczna próba nastąpi za 7 dni. Jeśli się nie powiedzie, subskrypcja zostanie wstrzymana." : date ? `Spróbujemy ponownie automatycznie ${date}. Możesz wcześniej zaktualizować metodę płatności.` : "Spróbujemy ponownie automatycznie. Możesz wcześniej zaktualizować metodę płatności.", noRetryAction: "Nie zaplanowaliśmy kolejnej próby. Zaktualizuj metodę płatności i dokończ płatność, aby kontynuować subskrypcję.", cta: "Zaktualizuj metodę płatności", outro: "Jeśli masz pytania, odpowiedz na tę wiadomość." }),
    (greeting) => ({ subject: "Your subscription payment failed", preheader: "Review your payment method to keep the subscription active.", heading: "Payment unsuccessful", greeting, intro: "We could not charge the next subscription cycle.", amountLine: (amount) => `Amount: ${amount}.`, noAmountLine: "We will try the payment again.", noAmountLineNoRetry: "This cycle remains unpaid.", methodLine: (scheme, digits) => `Payment method: ${method(scheme, digits)}.`, reassurance: (attempt, date) => attempt >= 3 ? date ? `The final automatic attempt is in 7 days, on ${date}. If it fails, the subscription will be paused.` : "The final automatic attempt is in 7 days. If it fails, the subscription will be paused." : date ? `We will retry automatically on ${date}. You can update the payment method first.` : "We will retry automatically. You can update the payment method first.", noRetryAction: "No further attempt is scheduled. Update the payment method and complete payment to continue the subscription.", cta: "Update payment method", outro: "Reply if you have questions." }),
  ),
  paymentRecovered: localized(greetings,
    (greeting) => ({ subject: "Płatność za subskrypcję pobrana", preheader: "Płatność się udała, a subskrypcja jest kontynuowana.", heading: "Płatność pobrana", greeting, intro: "Zaległa płatność za subskrypcję została pobrana.", detail: (amount) => [amount ? `Pobrana kwota: ${amount}.` : "Zaległy cykl został opłacony.", "Nie musisz nic robić. Harmonogram subskrypcji pozostaje aktywny."], outro: "Jeśli masz pytania o płatność, odpowiedz na tę wiadomość." }),
    (greeting) => ({ subject: "Subscription payment received", preheader: "Payment succeeded and the subscription continues.", heading: "Payment received", greeting, intro: "The outstanding subscription payment was collected.", detail: (amount) => [amount ? `Amount charged: ${amount}.` : "The outstanding cycle was paid.", "There is nothing you need to do. The subscription schedule remains active."], outro: "Reply if you have questions about this payment." }),
  ),
  renewalAtRisk: localized(greetings,
    (greeting) => ({ subject: "Zaktualizuj metodę płatności subskrypcji", preheader: "Nie możemy pobrać opłaty za najbliższe odnowienie.", heading: "Najbliższe odnowienie wymaga działania", greeting, intro: (date) => date ? `Odnowienie zaplanowano na ${date}, ale nie będziemy mogli pobrać opłaty.` : "Odnowienie jest blisko, ale nie będziemy mogli pobrać opłaty.", consequence: "Nic jeszcze nie zostało pobrane ani odrzucone. Dodaj metodę płatności przed odnowieniem, aby subskrypcja była kontynuowana.", cta: "Zaktualizuj metodę płatności", outro: "Jeśli potrzebujesz pomocy, odpowiedz na tę wiadomość." }),
    (greeting) => ({ subject: "Update your subscription payment method", preheader: "We cannot charge the next renewal.", heading: "Your next renewal needs attention", greeting, intro: (date) => date ? `Renewal is scheduled for ${date}, but we will not be able to collect payment.` : "Renewal is approaching, but we will not be able to collect payment.", consequence: "Nothing has been charged or declined. Add a payment method before renewal so the subscription can continue.", cta: "Update payment method", outro: "Reply if you need help." }),
  ),
} satisfies SubscriptionDunningEmailContent;
